import { nowIso } from './utils.js';

export function createDefaultState() {
  const createdAt = nowIso();
  return {
    schemaVersion: 3,
    activeProjectId: 'flare-demo',
    projects: [
      {
        id: 'flare-demo',
        name: 'Project Flare Demo',
        repoPath: '',
        unityProjectPath: '',
        docsPath: '',
        obsidianVaultPath: '',
        activeUpstreamId: 'anklebreaker-local',
        createdAt,
        updatedAt: createdAt,
      },
    ],
    documents: [
      {
        id: 'doc_agents',
        projectId: 'flare-demo',
        path: 'AGENTS.md',
        title: 'Agent Instructions',
        kind: 'agent_instruction',
        content: `# AGENTS.md\n\n## Roles\n- ChatGPT is the architect, designer, planner, and reviewer.\n- Codex is the implementer, refactorer, test runner, and Unity editor operator.\n\n## Unity Rules\n- Prefer Unity MCP/editor operations for scene, prefab, and serialized asset changes.\n- Prefer direct repo edits for code.\n- Check compilation after code changes.\n- Run focused EditMode or PlayMode tests when available.\n- Write a result note before marking a task done.\n\n## Project Rules\n- Keep gameplay systems modular and event-driven.\n- Avoid unrelated scene/prefab changes.\n- Do not install packages or modify project settings without explicit approval.\n`,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: 'doc_design',
        projectId: 'flare-demo',
        path: 'GAME_DESIGN.md',
        title: 'Game Design Notes',
        kind: 'design',
        content: `# Game Design Notes\n\nUse this document for high-level gameplay, combat, world, characters, and feel.\n`,
        createdAt,
        updatedAt: createdAt,
      },
      {
        id: 'doc_tech',
        projectId: 'flare-demo',
        path: 'TECHNICAL_DESIGN.md',
        title: 'Technical Design Notes',
        kind: 'technical',
        content: `# Technical Design Notes\n\nUse this document for architecture, systems, patterns, dependencies, and testing strategy.\n`,
        createdAt,
        updatedAt: createdAt,
      },
    ],
    tasks: [
      {
        id: 'task_demo',
        projectId: 'flare-demo',
        title: 'Wire Dev Hub to Unity MCP',
        parentTaskId: null,
        status: 'idea',
        designIntent: 'Verify the Dev Hub can list upstream Unity MCP tools and safely route role-filtered calls.',
        acceptanceCriteria: [
          'ChatGPT role can read docs and call only read-classified Unity tools.',
          'Codex role can call approved Unity tools.',
          'Audit logs are written for all MCP tool calls.',
        ],
        assignedTo: 'human',
        createdBy: 'human',
        completedAt: null,
        completedBy: null,
        changesRequestedAt: null,
        changesRequestedBy: null,
        reviewNote: '',
        archivedAt: null,
        archivedBy: null,
        createdAt,
        updatedAt: createdAt,
      },
    ],
    messages: [],
    decisions: [],
    upstreams: [
      {
        id: 'anklebreaker-local',
        projectId: 'flare-demo',
        name: 'AnkleBreaker Unity MCP Local',
        transport: 'streamable_http',
        url: 'http://localhost:8080/mcp',
        env: {},
        headers: {},
        enabled: false,
        semanticTools: {
          sceneOverview: '',
          consoleRead: '',
          screenshot: '',
          assetSearch: '',
          testResults: '',
        },
        policy: {
          toolProfile: 'anklebreaker-unity',
          chatFullAccess: false,
          defaultForChat: 'deny',
          defaultForCodex: 'allow',
          readPatterns: [
            'get_*',
            'list_*',
            'find_*',
            'inspect_*',
            'read_*',
            '*overview*',
            '*screenshot*',
            '*console*',
            '*log*',
            '*logs*',
            '*status*',
            '*test*result*',
          ],
          writePatterns: [
            'create_*',
            'set_*',
            'update_*',
            'delete_*',
            'add_*',
            'remove_*',
            'execute_*',
            'run_*',
            'build_*',
            '*write*',
            '*modify*',
          ],
          destructivePatterns: [
            'delete_*',
            'remove_*',
            '*destroy*',
            '*wipe*',
          ],
          overrides: {},
          codexRequiresConfirmationCategories: ['destructive'],
        },
        createdAt,
        updatedAt: createdAt,
      },
    ],
    auditLogs: [],
  };
}
